; Items
melee_mainhand := "["
excalibur := "]"
vigour := "F6"
rod := "F7"
chins := "="
mainhand := "i"
offhand := "o"
2h := "."
amulet_1 := "l"
amulet_2 := "n"
conc := ","
shield := "m"
helm := "PgDn"
body := "s"
legs := "Ins"
switch_offhand := "Delete"
switch_mainhand := "Home"

; Abilities
bladed_dive := ";"
planted_feet_ability := "6"
ingen := "p"
smoke_cloud := "u"
incend := "F3"
spec := "0"
essence_of_finality := "j"
mage_prayer := "F8"
ranged_prayer := "-"
